config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"

  resources :blogs
  
  get "inquiries", to: "inquiries#index"
  post 'inquiries', to: 'inquiries#index'
  post 'inquiries/confirm', to: 'inquiries#confirm'
  post 'inquiries/thanks', to: 'inquiries#thanks'
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base

  validates :name,  
  presence: { message: "名前の入力は必須です。" },
  length: { maximum: 15, message: "名前は15文字以内で入力ください。"  } 
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 
  presence: { message: "メールアドレスの入力は必須です。" },
  length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX, message: "有効なメールアドレスかご確認ください。", allow_blank: true}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
    
    def index
      if params[:back]
      @inquiry = Inquiry.new(inquiry_params)
      else 
      @inquiry = Inquiry.new
      end
    end
    
    def confirm
      @inquiry = Inquiry.new(inquiry_params)
      if @inquiry.valid?
      render 'confirm'
      else
      render 'index'
      end
    end
    
    def thanks
      @inquiry = Inquiry.create(inquiry_params)
    end
    
    
  private
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :content)
    end
    
    
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/inquiries/confirm.html.erb
<%= form_for @inquiry, :url => inquiries_thanks_path do |f| %>

<h1>お問い合わせ(再度内容をご確認ください)</h1>

<table>
  <tr>
    <th>名前</th>
    <td>
    <%= f.hidden_field :name %>
    <%= @inquiry.name %>
    </td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td>
    <%= f.hidden_field :email %>
    <%= @inquiry.email %>
    </td>
  </tr>
  <tr>
    <th>お問い合わせ内容</th>
    <td>
    <%= f.hidden_field :content %>
    <%= @inquiry.content %>
   </td>
  </tr>
</table>

<center>
<%= f.submit "この内容で登録する" %>

<% end %>

<%= form_for @inquiry, :url => inquiries_path do |f| %>

<%= f.hidden_field :name %>
<%= f.hidden_field :email %>
<%= f.hidden_field :content %>

<%= f.submit "やっぱり内容を修正する", name: 'back' %>

<% end %>
</center>

app/views/inquiries/index.html.erb
<%= form_for @inquiry, :url => inquiries_confirm_path do |f| %>

<h1>お問い合わせ</h1>

<table>
  <tr>
    <th><%= f.label :名前（必須） %></th>
    <td><%= f.text_field :name, :size => "30x1" %></td>
  </tr>
  <tr>
    <th><%= f.label :メールアドレス（必須） %></th>
    <td><%= f.text_field :email, :size => "30x1" %></td>
  </tr>
  <tr>
    <th><%= f.label :お問い合わせ内容 %></th>
    <td><%= f.text_area :content, :size => "60x6" %></td>
  </tr>
 
</table>
<br>
<% if @inquiry.errors.any? %>
  <div id="error_explanation">
    <div>
      <strong></strong>入力内容に <%= @inquiry.errors.count %>個のエラーがあります。</strong>
    </div>
    <ol>
    <% @inquiry.errors.each do |attribute, msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  </div>
<% end %>
<center>
<%= f.submit 'お問い合わせ送信' %>
</center>
<% end %>

app/views/inquiries/thanks.html.erb
<h1>お問い合わせ</h1>

<p>
  お問い合わせいただきありがとうございました。
</p>

<%= link_to '別のお問い合わせをする', inquiries_path %><br />
<%= link_to 'Topに戻る', root_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task13</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<h1>すべての人にテクノロジーという武器を</h1>
<p>dive into code</p>
<p><a href="/inquiries/">お問合せ</a></p>